Navigation test
Dufuna-CodeCamp/issue-tests pull request #4
Opened 2021-03-31 17:41 UTC by Morenayd

2021-04-01 12:20 UTC, Ireti203 requested changes

2021-04-01 12:20 UTC, Ireti203 commented on navigation-test/navigation_test.js
> +        const element = await driver.findElement(By.css("a[href='../introductionToHtml/e-commerceStore.Html']"));
This is not the common link for most scholars. I think you should update the link here. They should have a product.html file in the HTML folder. This particular scholar you used isn't doing the right thing.

2021-04-06 10:31 UTC, beccadaniel commented
@Morenayd 

1. `.DS_Store` shouldn't be pushed, we'll probably need to add a `.gitignore` file to avoid further occurrence in the future.
2. Your folder structure for test files should follow the convention, e.g. if you're working on issue 6, you should have a folder called `issue6` which will contain your js test.

2021-04-06 13:07 UTC, Ireti203 commented
@Morenayd This is issue4

2021-04-08 09:42 UTC, beccadaniel commented
@Morenayd  There's a conflict in this file. Please ensure this branch is up to date with the `master` branch

2021-04-08 09:56 UTC, beccadaniel requested changes

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +
Please remove these extra spaces.

2021-04-08 09:56 UTC, beccadaniel commented on README.md
> +- Folashade Daniel - [@beccadaniel](github.com/beccadaniel)
This file isn't up to date with the one in the master branch

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +        var file_url = `file:///Users/user/Downloads/Dufuna-CodeCamp20/submissions/oyetejuOloyede/htmlForms/contact.html`;
The `file_url` value shouldn't be an hardcoded value. You might want to check other test cases to see how this was implemented?

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +        const element = await driver.findElement(By.css("a[href='../htmlForms/contact.html']"));
Are we sure that the file will always be in a folder named `htmlForms` and will the file itself always be named `contact.html`?

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +        const element = await driver.findElement(By.css("a[href='../introductionToHtml/e-commerceStore.Html']"));
same here as the previous comment

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +        assert.include(link, "Product Page", `Ensure link is presnt` )
There's a typo here

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +        const element = await driver.findElement(By.css("a[href='../introductionToHtml/e-commerceStore.Html']"));
same comment here as previous comments

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +            const navigator =  driver.navigate().to('../introductionToHtml/e-commerceStore.Html');
same here as previous comments

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +                const expectedTitle = 'Smart Bookstore'
I'm not sure these tests are valid for our use case?

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +        const element = await driver.findElement(By.css("a[href='../htmlForms/contact.html']"))
same here as previous comments

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +            const navigator = driver.navigate().to('../htmlForms/contact.html');
same here as previous comments

2021-04-08 09:56 UTC, beccadaniel commented on issue4/navigation_test.js
> +                const expectedTitle = 'Contact Form'
Did we specify in the issue that the title should be `Contact Form`? If we didn't, then this might not be a general test case.

2021-04-08 09:58 UTC, beccadaniel commented
@Morenayd , you might want to remove files that have no content. Let's also try to have a convention for our PR-title. We can use issue names as PR-titles if the PR is specifically for an issue. That way, the reviewer knows what to look for in the test cases.

Well done on your first test nevertheless!

2021-04-14 06:39 UTC, closed without merging